module.exports = {
    ACCESS_TOKEM: "ACCESS_TOKEN",
    USER_ID: "USER_ID",
    JWT_SECRET: "AUTHOR_IS_JEALH",
    MAIL_USER: "ApFacTes@163.com",
    MAIL_PASS: "PMBXJNFNJOSXJZFH",
    MAIL_HOST: "smtp.163.com",
    MAIL_PORT: 465,
    MAIL_SERVICE: "163",
    SERVER_IP: '47.99.199.187',
    REDIS_PORT: 6379,
    REDIS_PASSWORD: 'hhd1620175472',
    TASK_FINISH: 'finish',
    TASK_UNDERWAY: 'underway'
}